// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgKbS2jX5QhyeRyUVMWY9O-7saeyU_UQ',
    appId: '1:975332429096:android:e8d7cc2eef5828df1b141d',
    messagingSenderId: '975332429096',
    projectId: 'momentum-9f21a',
    storageBucket: 'momentum-9f21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHndsoqqSId_3raE2BFPVLDXndDPuX_Y',
    appId: '1:975332429096:ios:e1027c18d2e79ed61b141d',
    messagingSenderId: '975332429096',
    projectId: 'momentum-9f21a',
    storageBucket: 'momentum-9f21a.firebasestorage.app',
    iosBundleId: 'com.sap70169004.momentum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlZYpMZ_ivzg4F8XBtY6OsJ7g3v3DZZQQ',
    appId: '1:975332429096:web:7fbd19691fee807d1b141d',
    messagingSenderId: '975332429096',
    projectId: 'momentum-9f21a',
    authDomain: 'momentum-9f21a.firebaseapp.com',
    storageBucket: 'momentum-9f21a.firebasestorage.app',
    measurementId: 'G-NGBX6SFX5R',
  );

}