// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIt-c6SySRGGK2Ow9TkSmEnVFc035NodA',
    appId: '1:156463184352:web:191eb60ab61dd5b4121385',
    messagingSenderId: '156463184352',
    projectId: 'nexus-85e31',
    authDomain: 'nexus-85e31.firebaseapp.com',
    storageBucket: 'nexus-85e31.firebasestorage.app',
    measurementId: 'G-0TS7K7N8QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuIr0dYsIGaFxHwvCAa8BxiRyJY9acF4',
    appId: '1:156463184352:android:71573d804da3545c121385',
    messagingSenderId: '156463184352',
    projectId: 'nexus-85e31',
    storageBucket: 'nexus-85e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB9gj296bh24c0vIgOi7rjrW1PLicRsy4',
    appId: '1:156463184352:ios:c2f030557da61bc6121385',
    messagingSenderId: '156463184352',
    projectId: 'nexus-85e31',
    storageBucket: 'nexus-85e31.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB9gj296bh24c0vIgOi7rjrW1PLicRsy4',
    appId: '1:156463184352:ios:c2f030557da61bc6121385',
    messagingSenderId: '156463184352',
    projectId: 'nexus-85e31',
    storageBucket: 'nexus-85e31.firebasestorage.app',
    iosBundleId: 'com.example.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIt-c6SySRGGK2Ow9TkSmEnVFc035NodA',
    appId: '1:156463184352:web:e278042d5ce3a9bc121385',
    messagingSenderId: '156463184352',
    projectId: 'nexus-85e31',
    authDomain: 'nexus-85e31.firebaseapp.com',
    storageBucket: 'nexus-85e31.firebasestorage.app',
    measurementId: 'G-1P3F2X7MZF',
  );

}