// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-t4ilUr_D3cYodoJJTyosqIa7cTD0Ko',
    appId: '1:482178776460:web:37deb608a85d11d2a82aa9',
    messagingSenderId: '482178776460',
    projectId: 'eventhub-11386',
    authDomain: 'eventhub-11386.firebaseapp.com',
    storageBucket: 'eventhub-11386.firebasestorage.app',
    measurementId: 'G-M39ZC75LYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Lew6rAPqEy9P3QDlGROG1-bdYBtdd0Q',
    appId: '1:482178776460:android:3672b153121dc82ea82aa9',
    messagingSenderId: '482178776460',
    projectId: 'eventhub-11386',
    storageBucket: 'eventhub-11386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxIar0wdTq-B_EAnd6Q2EnhtMKCaa4Nw',
    appId: '1:482178776460:ios:850e9c8d655e9a03a82aa9',
    messagingSenderId: '482178776460',
    projectId: 'eventhub-11386',
    storageBucket: 'eventhub-11386.firebasestorage.app',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhxIar0wdTq-B_EAnd6Q2EnhtMKCaa4Nw',
    appId: '1:482178776460:ios:850e9c8d655e9a03a82aa9',
    messagingSenderId: '482178776460',
    projectId: 'eventhub-11386',
    storageBucket: 'eventhub-11386.firebasestorage.app',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5-t4ilUr_D3cYodoJJTyosqIa7cTD0Ko',
    appId: '1:482178776460:web:578ebf46d5a38161a82aa9',
    messagingSenderId: '482178776460',
    projectId: 'eventhub-11386',
    authDomain: 'eventhub-11386.firebaseapp.com',
    storageBucket: 'eventhub-11386.firebasestorage.app',
    measurementId: 'G-9R0F8Q145C',
  );
}
