// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIwpnpmVehPH_Weke7AXD4pNaiiF9CwI8',
    appId: '1:1085566411592:web:41e9b2d634c6f944e3497d',
    messagingSenderId: '1085566411592',
    projectId: 'getcars-c4d3b',
    authDomain: 'getcars-c4d3b.firebaseapp.com',
    storageBucket: 'getcars-c4d3b.firebasestorage.app',
    measurementId: 'G-9LVXT74HJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnBpMqGIhoZBrZx-LbGGFwydRX1KMjM98',
    appId: '1:1085566411592:android:3502185fe9ddb336e3497d',
    messagingSenderId: '1085566411592',
    projectId: 'getcars-c4d3b',
    storageBucket: 'getcars-c4d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FPWoLWETPi55hKLev_EArALqRiCQfEg',
    appId: '1:1085566411592:ios:09a9d9f06d10d675e3497d',
    messagingSenderId: '1085566411592',
    projectId: 'getcars-c4d3b',
    storageBucket: 'getcars-c4d3b.firebasestorage.app',
    iosBundleId: 'com.example.olxapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7FPWoLWETPi55hKLev_EArALqRiCQfEg',
    appId: '1:1085566411592:ios:09a9d9f06d10d675e3497d',
    messagingSenderId: '1085566411592',
    projectId: 'getcars-c4d3b',
    storageBucket: 'getcars-c4d3b.firebasestorage.app',
    iosBundleId: 'com.example.olxapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIwpnpmVehPH_Weke7AXD4pNaiiF9CwI8',
    appId: '1:1085566411592:web:4f99ae7f9514fd70e3497d',
    messagingSenderId: '1085566411592',
    projectId: 'getcars-c4d3b',
    authDomain: 'getcars-c4d3b.firebaseapp.com',
    storageBucket: 'getcars-c4d3b.firebasestorage.app',
    measurementId: 'G-EFQBLZYEZX',
  );
}
