// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDq1YwedHGEZB7puQcQWwEyQur1J86k0',
    appId: '1:34996144772:web:80d5181752a84f70ded0d1',
    messagingSenderId: '34996144772',
    projectId: 'knowbase-app-47444',
    authDomain: 'knowbase-app-47444.firebaseapp.com',
    storageBucket: 'knowbase-app-47444.firebasestorage.app',
    measurementId: 'G-4F7J4BLQ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYimzOZG3TFsufwEQSmRrTEzNx6WCi7Y',
    appId: '1:34996144772:android:2bbbb85b33ceb2fbded0d1',
    messagingSenderId: '34996144772',
    projectId: 'knowbase-app-47444',
    storageBucket: 'knowbase-app-47444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6OehTSIpkO0gwnq7iMYnoDeLCvPQ0YUE',
    appId: '1:34996144772:ios:f9875f12b1cc4563ded0d1',
    messagingSenderId: '34996144772',
    projectId: 'knowbase-app-47444',
    storageBucket: 'knowbase-app-47444.firebasestorage.app',
    iosBundleId: 'com.example.figmapp.figmaToFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6OehTSIpkO0gwnq7iMYnoDeLCvPQ0YUE',
    appId: '1:34996144772:ios:92d8bc76a16a9613ded0d1',
    messagingSenderId: '34996144772',
    projectId: 'knowbase-app-47444',
    storageBucket: 'knowbase-app-47444.firebasestorage.app',
    iosBundleId: 'com.example.figmaToFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDDq1YwedHGEZB7puQcQWwEyQur1J86k0',
    appId: '1:34996144772:web:481273c4d482a30fded0d1',
    messagingSenderId: '34996144772',
    projectId: 'knowbase-app-47444',
    authDomain: 'knowbase-app-47444.firebaseapp.com',
    storageBucket: 'knowbase-app-47444.firebasestorage.app',
    measurementId: 'G-X70QSF8GSM',
  );
}
